config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#Dashboard"
  get "about" => "pages#About"
  get "messages" => "pages#Messages"
  get "settings" => "pages#Settings"
  get "trending" => "pages#Trending"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def Dashboard
  end

  def Trending
  end

  def Messages
  end

  def Settings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ext-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <div class="container-fluid" style="padding-bottom:20px;margin-top:-14px;">
          <div class="navbar-header">
            <a class="navbar-brand" href="/">
              <img src ="https://secure.assets.tumblr.com/images/logo/logo_large.png?v=7ea0eb57dd627a95f82be5bde0c43d59">
            </a>
          </div>
        </div>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
        <% if user_signed_in? %>
            <div class="collapse navbar-collapse navbar-ext-collapse">
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Dashboard", root_path %></li>
                <li><%= link_to "Trending", trending_path %></li>
                <li><%= link_to "Messages", messages_path %></li>
                <li><%= link_to "Account", settings_path %></li>
                <li><%= link_to "Log Out", destroy_user_session_path, method:  :delete %></li>
                  </ul>       
            </div><!-- /.navbar-collapse -->
          <% else %>
          <div class="collapse navbar-collapse navbar-ext-collapse">
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Login", new_user_session_path %></li>
              </ul>       
            </div><!-- /.navbar-collapse -->

        <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pintumblr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <%# For Mobile Responsiveness %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
<body>
<%# Navigation Main %>
<%= render 'layouts/header' %>
<%# Body Page Container ======================= %>	
	<div class="container">
<%# Flash Messages for Devise ================= %>
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
<%# Page Information Loop =================== %>
		<%= yield %>
</body>
</html>

app/views/pages/Dashboard.html.erb
<div class="jumbotron center">
		<% if user_signed_in? %>
		# Congratulatioons You Have Sold Your Soul
		<% else %>
			<div class="container text-center"
							<p>
						<h1 align= "center">Welcome To PinTumblr</h1>
						<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
						<%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
					</p>
			</div>
		<% end %>


</div>

app/views/pages/Messages.html.erb
<div class="jumbotron">
<h1>Pages#Messages</h1>
<p>Find me in app/views/pages/Messages.html.erb</p>
</div>

app/views/pages/Settings.html.erb
<div class="jumbotron">
<h1>Pages#Settings</h1>
<p>Find me in app/views/pages/Settings.html.erb</p>
</div>

app/views/pages/Trending.html.erb
<div class="jumbotron">
<h1>Pages#Trending</h1>
<p>Find me in app/views/pages/Trending.html.erb</p>
</div>